name: Python application

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script to fetch data
      run: |
        python search_script.py

    - name: Save results
      run: |
        # Move the JSON file to the root directory or any desired location
        mv search_results.json ./path/to/directory/

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add ./path/to/directory/search_results.json
        git commit -m "Atualizar arquivo JSON com resultados de pesquisa"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
